### ISSUE TITLE
Connect over docker network

### ISSUE THREAD

**Issue by SplinterHead** [mayswind/AriaNg#718]
I'm trying to connect AriaNG to Aria2 over an isolated Docker netwotk (no ports exposed to the host).
I'm struggling to get it to connect, is there any reason to expect the ports are to be exposed?

Docker compose sample:
```yaml
services:
  aria2:
    image: <self-built aria2 image>
    container_name: aria2
    networks:
      - aria
    ...
  aria-ng:
    image: <self-built ariang image>
    container_name: ariang
    networks:
      - public
      - aria
    ...

networks:
  public:
    external: true # Ingress from public internet via reverse proxy
  aria:
    external: true # Isolated network for communication between these two containers
```
